name: Deploy VitePress to Pages

on:
  push:
    branches:
      - book

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: book/pnpm-lock.yaml

      - name: Install Dependencies
        working-directory: book
        run: pnpm install --frozen-lockfile

      - name: Build VitePress Site
        working-directory: book
        run: pnpm run docs:build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: book/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5